### ISSUE TITLE
I know it's strange to get in contact with you here but I think you could help me

### ISSUE THREAD

**Issue by Kryvonis** [mefistotelis/swars-re-helpers#2]
I have a problem with DJI Mavic 2, I need to switch it to ATTI mode and I found that project https://github.com/o-gs/dji-firmware-tools. 
I think it's my last hope. Please reach me out here `kryvonis.artem@gmail.com` if you could provide some information.

Thank you and sorry for creating issue

**Comment by mefistotelis** [comment]
Create an issue in correct project. You may also want to join Mattermost, and ask there - find related links in other issues.
